name: pytest

on:
  pull_request

jobs:
  pytest:
    name: Run Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1

      - name: Install Dependencies
        run: |
          cd app/backend
          poetry install --no-interaction

      - name: Run Pytest
        run: poetry run pytest test --junit-xml coverage/pytest.xml
        continue-on-error: true

      - name: Upload Test Coverage
        uses: actions/upload-artifact@v3
        with:
          name: test_coverage
          path: coverage/*.xml

      - name: Download Test Coverage
        uses: actions/download-artifact@v3
        with:
          name: test_coverage
          path: artifacts

      - name: Display Test Coverage
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml
